indices:
    TAIR10: "/prog/BIF30806/project/groen_team/kallisto_index/TAIR10.idx"
    Araport11: "/prog/BIF30806/project/groen_team/kallisto_index/Araport11.idx"
genomes:
    - 'TAIR10'
    - 'Araport11'
metadata: "/prog/BIF30806/project/groen_team/metadata.txt"
samples:
    A-10R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-10R3_R1.fastq.gz"
    A-10R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-10R5_R1.fastq.gz"
    A-11R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-11R1_R1.fastq.gz"
    A-11R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-11R5_R1.fastq.gz"
    A-12R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-12R1_R1.fastq.gz"
    A-12R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-12R2_R1.fastq.gz"
    A-12R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-12R4_R1.fastq.gz"
    A-12R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-12R5_R1.fastq.gz"
    A-14R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-14R1_R1.fastq.gz"
    A-14R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-14R2_R1.fastq.gz"
    A-14R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-14R4_R1.fastq.gz"
    A-15R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-15R1_R1.fastq.gz"
    A-15R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-15R4_R1.fastq.gz"
    A-16R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-16R3_R1.fastq.gz"
    A-16R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-16R4_R1.fastq.gz"
    A-16R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-16R5_R1.fastq.gz"
    A-17R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-17R1_R1.fastq.gz"
    A-17R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-17R2_R1.fastq.gz"
    A-17R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-17R3_R1.fastq.gz"
    A-17R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-17R4_R1.fastq.gz"
    A-18R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-18R1_R1.fastq.gz"
    A-18R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-18R4_R1.fastq.gz"
    A-18R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-18R5_R1.fastq.gz"
    A-19R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-19R1_R1.fastq.gz"
    A-19R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-19R2_R1.fastq.gz"
    A-19R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-19R4_R1.fastq.gz"
    A-19R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-19R5_R1.fastq.gz"
    A-1R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-1R2_R1.fastq.gz"
    A-1R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-1R4_R1.fastq.gz"
    A-1R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-1R5_R1.fastq.gz"
    A-20R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-20R1_R1.fastq.gz"
    A-20R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-20R3_R1.fastq.gz"
    A-20R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-20R4_R1.fastq.gz"
    A-21R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-21R1_R1.fastq.gz"
    A-21R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-21R3_R1.fastq.gz"
    A-21R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-21R4_R1.fastq.gz"
    A-22R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-22R1_R1.fastq.gz"
    A-22R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-22R2_R1.fastq.gz"
    A-22R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-22R3_R1.fastq.gz"
    A-22R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-22R5_R1.fastq.gz"
    A-23R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-23R1_R1.fastq.gz"
    A-23R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-23R2_R1.fastq.gz"
    A-23R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-23R3_R1.fastq.gz"
    A-23R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-23R4_R1.fastq.gz"
    A-23R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-23R5_R1.fastq.gz"
    A-24R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-24R1_R1.fastq.gz"
    A-24R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-24R2_R1.fastq.gz"
    A-24R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-24R3_R1.fastq.gz"
    A-24R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-24R4_R1.fastq.gz"
    A-24R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-24R5_R1.fastq.gz"
    A-25R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-25R2_R1.fastq.gz"
    A-25R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-25R3_R1.fastq.gz"
    A-25R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-25R4_R1.fastq.gz"
    A-25R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-25R5_R1.fastq.gz"
    A-26R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-26R1_R1.fastq.gz"
    A-26R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-26R2_R1.fastq.gz"
    A-26R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-26R3_R1.fastq.gz"
    A-27R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-27R1_R1.fastq.gz"
    A-27R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-27R2_R1.fastq.gz"
    A-27R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-27R4_R1.fastq.gz"
    A-27R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-27R5_R1.fastq.gz"
    A-28R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-28R2_R1.fastq.gz"
    A-28R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-28R3_R1.fastq.gz"
    A-28R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-28R4_R1.fastq.gz"
    A-28R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-28R5_R1.fastq.gz"
    A-29R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-29R1_R1.fastq.gz"
    A-29R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-29R2_R1.fastq.gz"
    A-29R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-29R3_R1.fastq.gz"
    A-29R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-29R4_R1.fastq.gz"
    A-2R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-2R1_R1.fastq.gz"
    A-2R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-2R2_R1.fastq.gz"
    A-2R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-2R3_R1.fastq.gz"
    A-2R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-2R4_R1.fastq.gz"
    A-2R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-2R5_R1.fastq.gz"
    A-30R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-30R1_R1.fastq.gz"
    A-30R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-30R2_R1.fastq.gz"
    A-30R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-30R3_R1.fastq.gz"
    A-30R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-30R4_R1.fastq.gz"
    A-30R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-30R5_R1.fastq.gz"
    A-31R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-31R1_R1.fastq.gz"
    A-31R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-31R2_R1.fastq.gz"
    A-31R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-31R4_R1.fastq.gz"
    A-32R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-32R2_R1.fastq.gz"
    A-32R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-32R5_R1.fastq.gz"
    A-33R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-33R2_R1.fastq.gz"
    A-33R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-33R4_R1.fastq.gz"
    A-33R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-33R5_R1.fastq.gz"
    A-34R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-34R1_R1.fastq.gz"
    A-34R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-34R3_R1.fastq.gz"
    A-34R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-34R4_R1.fastq.gz"
    A-35R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-35R1_R1.fastq.gz"
    A-35R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-35R3_R1.fastq.gz"
    A-35R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-35R4_R1.fastq.gz"
    A-35R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-35R5_R1.fastq.gz"
    A-36R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-36R1_R1.fastq.gz"
    A-36R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-36R4_R1.fastq.gz"
    A-37R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-37R2_R1.fastq.gz"
    A-37R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-37R3_R1.fastq.gz"
    A-37R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-37R5_R1.fastq.gz"
    A-38R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-38R1_R1.fastq.gz"
    A-38R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-38R2_R1.fastq.gz"
    A-38R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-38R3_R1.fastq.gz"
    A-38R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-38R5_R1.fastq.gz"
    A-39R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-39R3_R1.fastq.gz"
    A-39R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-39R5_R1.fastq.gz"
    A-3R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-3R2_R1.fastq.gz"
    A-3R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-3R3_R1.fastq.gz"
    A-3R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-3R5_R1.fastq.gz"
    A-40R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-40R2_R1.fastq.gz"
    A-40R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-40R3_R1.fastq.gz"
    A-40R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-40R4_R1.fastq.gz"
    A-40R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-40R5_R1.fastq.gz"
    A-4R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-4R1_R1.fastq.gz"
    A-4R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-4R3_R1.fastq.gz"
    A-4R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-4R4_R1.fastq.gz"
    A-4R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-4R5_R1.fastq.gz"
    A-5R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-5R2_R1.fastq.gz"
    A-5R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-5R4_R1.fastq.gz"
    A-5R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-5R5_R1.fastq.gz"
    A-6R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-6R2_R1.fastq.gz"
    A-6R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-6R3_R1.fastq.gz"
    A-6R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-6R5_R1.fastq.gz"
    A-7R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-7R1_R1.fastq.gz"
    A-7R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-7R4_R1.fastq.gz"
    A-7R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-7R5_R1.fastq.gz"
    A-8R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-8R1_R1.fastq.gz"
    A-8R2: "/prog/BIF30806/project/data/transcriptome/20180605.A-8R2_R1.fastq.gz"
    A-8R3: "/prog/BIF30806/project/data/transcriptome/20180605.A-8R3_R1.fastq.gz"
    A-8R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-8R4_R1.fastq.gz"
    A-8R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-8R5_R1.fastq.gz"
    A-9R1: "/prog/BIF30806/project/data/transcriptome/20180605.A-9R1_R1.fastq.gz"
    A-9R4: "/prog/BIF30806/project/data/transcriptome/20180605.A-9R4_R1.fastq.gz"
    A-9R5: "/prog/BIF30806/project/data/transcriptome/20180605.A-9R5_R1.fastq.gz"
    A-10R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-10R1_R1.fastq.gz"
    A-10R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-10R2_R1.fastq.gz"
    A-10R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-10R4_R1.fastq.gz"
    A-11R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-11R2_R1.fastq.gz"
    A-11R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-11R3_R1.fastq.gz"
    A-11R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-11R4_R1.fastq.gz"
    A-12R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-12R3_R1.fastq.gz"
    A-13R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-13R1_R1.fastq.gz"
    A-13R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-13R2_R1.fastq.gz"
    A-13R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-13R3_R1.fastq.gz"
    A-13R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-13R4_R1.fastq.gz"
    A-13R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-13R5_R1.fastq.gz"
    A-14R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-14R3_R1.fastq.gz"
    A-14R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-14R5_R1.fastq.gz"
    A-15R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-15R2_R1.fastq.gz"
    A-15R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-15R3_R1.fastq.gz"
    A-15R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-15R5_R1.fastq.gz"
    A-16R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-16R1_R1.fastq.gz"
    A-16R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-16R2_R1.fastq.gz"
    A-17R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-17R5_R1.fastq.gz"
    A-18R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-18R2_R1.fastq.gz"
    A-18R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-18R3_R1.fastq.gz"
    A-19R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-19R3_R1.fastq.gz"
    A-1R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-1R1_R1.fastq.gz"
    A-1R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-1R3_R1.fastq.gz"
    A-20R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-20R2_R1.fastq.gz"
    A-20R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-20R5_R1.fastq.gz"
    A-21R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-21R2_R1.fastq.gz"
    A-21R4_p2663_4256_189: "/prog/BIF30806/project/data/transcriptome/20180613.A-21R4_p2663_4256_189_R1.fastq.gz"
    A-21R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-21R5_R1.fastq.gz"
    A-22R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-22R4_R1.fastq.gz"
    A-25R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-25R1_R1.fastq.gz"
    A-26R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-26R4_R1.fastq.gz"
    A-26R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-26R5_R1.fastq.gz"
    A-27R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-27R3_R1.fastq.gz"
    A-28R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-28R1_R1.fastq.gz"
    A-29R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-29R5_R1.fastq.gz"
    A-31R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-31R3_R1.fastq.gz"
    A-31R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-31R5_R1.fastq.gz"
    A-32R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-32R1_R1.fastq.gz"
    A-32R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-32R3_R1.fastq.gz"
    A-32R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-32R4_R1.fastq.gz"
    A-33R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-33R1_R1.fastq.gz"
    A-33R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-33R3_R1.fastq.gz"
    A-34R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-34R2_R1.fastq.gz"
    A-34R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-34R5_R1.fastq.gz"
    A-35R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-35R2_R1.fastq.gz"
    A-36R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-36R2_R1.fastq.gz"
    A-36R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-36R3_R1.fastq.gz"
    A-36R5: "/prog/BIF30806/project/data/transcriptome/20180613.A-36R5_R1.fastq.gz"
    A-37R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-37R1_R1.fastq.gz"
    A-37R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-37R4_R1.fastq.gz"
    A-39R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-39R1_R1.fastq.gz"
    A-39R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-39R2_R1.fastq.gz"
    A-39R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-39R4_R1.fastq.gz"
    A-3R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-3R1_R1.fastq.gz"
    A-3R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-3R4_R1.fastq.gz"
    A-40R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-40R1_R1.fastq.gz"
    A-4R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-4R2_R1.fastq.gz"
    A-5R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-5R1_R1.fastq.gz"
    A-5R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-5R3_R1.fastq.gz"
    A-6R1: "/prog/BIF30806/project/data/transcriptome/20180613.A-6R1_R1.fastq.gz"
    A-6R4: "/prog/BIF30806/project/data/transcriptome/20180613.A-6R4_R1.fastq.gz"
    A-7R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-7R2_R1.fastq.gz"
    A-7R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-7R3_R1.fastq.gz"
    A-9R2: "/prog/BIF30806/project/data/transcriptome/20180613.A-9R2_R1.fastq.gz"
    A-9R3: "/prog/BIF30806/project/data/transcriptome/20180613.A-9R3_R1.fastq.gz"
